# content of pytest.ini
[pytest]
markers =
    internal: mark a test as a test to private/internal functions.

# Add the following to suppress warnings
filterwarnings =
    ignore::FutureWarning
    ignore::DeprecationWarning
    ignore:.*torch.library.impl_abstract.*:FutureWarning
    ignore:.*torch.cuda.amp.custom_fwd.*:FutureWarning
    ignore:.*torch.cuda.amp.custom_bwd.*:FutureWarning
addopts = --disable-warnings